export const WORD_ADD_TOOLTIP = 'Здесь можно добавить новое слово';
export const WORD_LIST_TOOLTIP = 'Список всех слов с возможностью редактирования и удаления слов';
export const WORD_MATCH_TOOLTIP = 'Режим игры, в котором необходимо найти слово на английском и его перевод';
export const WORD_SELECT_TOOLTIP = 'Режим игры, в котором необходимо выбрать верный вариант перевода из предложенных';
export const WORD_SETTINGS_TOOLTIP = 'Внутриигровые настройки';
export const SETTINGS_GAMESET_COUNT = 'Определяет, сколько слов будет взято из базы данных для игры при выборе игрового режима';
export const SETTINGS_HARD_MODE = 'Усложняет режим "Выбери вариант" вариантом "Нет правильного перевода"';
export const SETTINGS_WORDS_PER_PAGE = 'Определяет, сколько слов будет показано на каждой странице во вкладке "Все слова"';
export const SETTINGS_WRONG_COUNT_PRIORITY = 'При выборе слов приоритет отдаётся словам с наибольшим числом неправильных отгадываний';